# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.41.0"

default_platform :ios

platform :ios do
  before_all do
    update_fastlane
    # carthage(
    #   command: "bootstrap",
    #   platform: "iOS",
    #   use_binaries: false
    # )
    match(git_url: "git@bitbucket.org:doron_katz/my-fastlane-keys.git",
      type: "adhoc",
      app_identifier: "com.doronkatz.firefox")
  end

  desc "Runs all the tests"
  lane :test do
    scan
  end

  lane :gen_screenshots do
    snapshot
    frameit(white: true, path: './fastlane/screenshots')
  end

  lane :build do
    gym(scheme: "Fennec",
      output_name:"firefox.ipa",
      silent: false,
      export_method: "ad-hoc",
      output_directory: "./Export"
        )
  end
  lane :beta do
    ensure_git_status_clean
    git_pull
    register_devices(devices_file: "devices.txt")
    gym(scheme: "Fennec",
        output_name:"firefox.ipa",
        export_method: "ad-hoc",
        silent: false,
        output_directory: "./Export"
      )
    scan
    changelog = changelog_from_git_commits(pretty: '%h %s')
    testflight(
      username: "doronkatz@mac.com",
      app_identifier: "com.doronkatz.firefox",
      beta_app_description: changelog,
      beta_app_feedback_email: "feedback@firefoxapp.com",
      itc_provider: "abcde12345" # pass a specific value to the iTMSTransporter -itc_provider option
    )
      
    increment_build_number(xcodeproj: "Client.xcodeproj")
    commit_version_bump(
      message: 'Build Version Bump by fastlane',
      xcodeproj: "Client.xcodeproj",
      force: true
    )
    add_git_tag(grouping: "testing")
    push_to_git_remote
    push_git_tags
  end

  lane :release do
    # by default deliver will call precheck and warn you of any problems
    # if you want precheck to halt submitting to app review, you can pass
    # precheck_default_rule_level: :error
    deliver(precheck_default_rule_level: :error)
    snapshot
    produce(
      username: 'doronkatz@mac.com',
      app_identifier: 'com.doronkatz.firefox',
      app_name: 'Firefox for iOS',
      language: 'English',
      app_version: '1.0',
      team_name: 'Doron Katz' # only necessary when in multiple teams
    )
    deliver(
      submit_for_review: true,
      force: true,
      metadata_path: "./metadata"
    )
  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used. No personal data is recorded. 
# Learn more at https://github.com/fastlane/fastlane#metrics
