# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.41.0"

default_platform :ios

platform :ios do
  ############################## PRE ##############################
  before_all do
    update_fastlane
    git_pull
    carthage(
      command: "bootstrap",
      platform: "iOS",
      use_binaries: false
    )
    match(git_url: "git@bitbucket.org:doron_katz/my-fastlane-keys.git",
      type: "adhoc",
      app_identifier: CredentialsManager::AppfileConfig.try_fetch_value(:app_identifier))
      test
  end

#------------------------- Test -------------------------#
  desc "Runs all the tests"
  lane :test do
    build
    scan
    post_to_slack(message: "Successfuly ran all the unit tests", success: true, payload: {})
  end

  #------------------------- Screenshots -------------------------#
  lane :gen_screenshots do
    snapshot
    frameit(white: true, path: './fastlane/screenshots')
    post_to_slack(message: "Successfuly generated new screenshots", success: true, payload: {})
  end

  #------------------------- Build -------------------------#
  lane :build do
    gym
    post_to_slack(message: "Successfuly completed a new build", success: true, payload: {})

  end

  ############################## DISTRIBUTION ##############################

  #------------------------- Beta -------------------------#
  lane :beta do
    register_devices(devices_file: "devices.txt")
    gym
    testflight(
      username: CredentialsManager::AppfileConfig.try_fetch_value(:apple_id),
      app_identifier: CredentialsManager::AppfileConfig.try_fetch_value(:app_identifier),
      beta_app_description: changelog,
      beta_app_feedback_email: "feedback@firefoxapp.com",
      itc_provider: "abcde12345" # pass a specific value to the iTMSTransporter -itc_provider option
      )
      
    increment_build_number(xcodeproj: "Client.xcodeproj")
    commit_version_bump(
      message: 'Build Version Bump by fastlane',
      xcodeproj: "Client.xcodeproj",
      force: true
    )
    changelog = changelog_from_git_commits(pretty: '%h %s')
    add_git_tag(grouping: "testing")
    post_to_slack(message: "Distributed new build to TestFlight.", success: true, payload: {"changelog": changelog, "build": get_build_number, "version": get_version_number})
  end

  #------------------------- App Store -------------------------#
  lane :release do
    # by default deliver will call precheck and warn you of any problems
    # if you want precheck to halt submitting to app review, you can pass
    # precheck_default_rule_level: :error
    deliver(precheck_default_rule_level: :error)
    gen_screenshots
    produce(
      username: CredentialsManager::AppfileConfig.try_fetch_value(:apple_id),
      app_identifier: CredentialsManager::AppfileConfig.try_fetch_value(:app_identifier),
      app_name: 'Firefox for iOS',
      language: 'English',
      app_version: '1.0',
      team_name: 'Doron Katz' # only necessary when in multiple teams
    )
    deliver(
      submit_for_review: true,
      force: true,
      metadata_path: "./metadata"
    )
  end

  ############################## POST ##############################
  
  after_all do |lane|
    changelog = changelog_from_git_commits(pretty: '%h %s')

    commit_version_bump(
      message: 'Build Version Bump by fastlane',
      xcodeproj: "Client.xcodeproj",
      force: true
    )
    post_to_slack(message: "Successfuly ran fastlane with lane '#(lane).", success: true, payload: {"lane": lane})
    push_to_git_remote
  end

  ############################## EXCEPTION HANDLING ##############################
  error do |lane, exception|
    post_to_slack(message: "fastlane encountered the error ‘#(exception)’ emanating from the lane ‘#(lane)’.", success: true, payload: {“exception”: exception, “lane”: lane})
  end
end

############################## PRIVATE LANES ##############################
#------------------------- post_to_slack -------------------------#
private_lane :post_to_slack do |options|
    message = options[:message]
    success = options[:success]
    payload = options[:payload]
    version     = get_version_number(xcodeproj: "Client.xcodeproj")
    build       = get_build_number(xcodeproj: "Client.xcodeproj")
    slack(
      message: message + " :" + version + ":" + build,
      slack_url: "https://hooks.slack.com/services/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",    
      success: success,
      payload: payload)
end
